package form;
import konfigurasi.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.text.*;
import java.io.*;
import java.net.*;
import java.util.*;
import javax.swing.*;

public class Utama extends JFrame {
    Connection conn;
    Statement stat;
    ResultSet set;
    DefaultTableModel isi;
    Object[] title= {"No Tiket","No Pol","Jenis","Tgl Masuk","Jam Masuk","Tgl Keluar","Jam Keluar"};
    
    public void buka_database(){
        try{
            Koneksi konek = new Koneksi("parkir_db");
            conn=konek.aktifkan_koneksi();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Failed to connect"); 
        }
    }
    final void tampil_parkir(){
        isi=new DefaultTableModel(null,title);
        try{
            stat = conn.createStatement();
            String perintah="SELECT * from parkir order by no_tiket desc";
            set = stat.executeQuery(perintah);
            while(set.next()){
                String dbnotik =set.getString("no_tiket");
                String dbnopol =set.getString("nopol");
                String dbjenis =set.getString("jenis");
                String dbtgl_msk =set.getString("tgl_masuk");
                String dbjam_msk =set.getString("jam_masuk");
                String dbtgl_klr =set.getString("tgl_keluar");
                String dbjam_klr =set.getString("jam_keluar");

                String[] data ={dbnotik,dbnopol,dbjenis,dbtgl_msk,dbjam_msk,dbtgl_klr,dbjam_klr};
                isi.addRow(data);
            }

        }catch(Exception e){
            System.out.println("Failed to retrieve data :  "+e);
            System.exit(0);
        }
        tabel_parkir.setModel(isi);
    }
    
    final void dapatkan_data(){
        isi = new DefaultTableModel(null,title);
        try{
            stat = conn.createStatement();
            String perintah="SELECT  tgl_keluar, jam_keluar, TIME_FORMAT(`jam_keluar`,'%H')-TIME_FORMAT(`jam_masuk`,'%H') AS durasi FROM parkir where nopol='"+cari.getText()+"';";
            set =stat.executeQuery(perintah);
            while(set.next()){
                kkeluar_tgl.setText(set.getString("tgl_keluar"));
                kkeluar_jam.setText(set.getString("jam_keluar"));
                durasi.setText(set.getString("durasi"));
            }

        }catch(Exception e){
            System.out.println("Failed to retrieve data :  "+e);
            System.exit(0);
        }
        tabel_parkir.setModel(isi);
    }
    
    public void cari_data(){
        isi=new DefaultTableModel(null,title);
        try{
           stat = conn.createStatement();
           String perintah="select * from parkir where nopol like '%"+cari.getText()+"%'";
           set = stat.executeQuery(perintah);
           while(set.next()){
                String dbnotik =set.getString("no_tiket");
                String dbnopol =set.getString("nopol");
                String dbjenis =set.getString("jenis");
                String dbtgl_msk =set.getString("tgl_masuk");
                String dbjam_msk =set.getString("jam_masuk");
                String dbtgl_klr =set.getString("tgl_keluar");
                String dbjam_klr =set.getString("jam_keluar");

                String[] data ={dbnotik,dbnopol,dbjenis,dbtgl_msk,dbjam_msk,dbtgl_klr,dbjam_klr};
                isi.addRow(data);
           }
        }catch(Exception e){
           System.out.println("Failed to retrieve data :  "+e);
           System.exit(0);
       }
       tabel_parkir.setModel(isi);
    }
    public void akumulasi_biaya(){
        int vdurasi;
        double vbj, vbiaya;
        
        vdurasi=Integer.parseInt(durasi.getText());
        vbj=Double.parseDouble(kbj.getText());
        
        if(vdurasi<=1){
            vbiaya=vbj;
        }else{
            vbiaya=(vbj)+((vdurasi-1)*2000);
        }
        biaya.setText(""+vbiaya);
    }
    
    public void bersih(){
        cari.setText("");
        kjenis.setText("");
        kbj.setText("");
        kkeluar_jam.setText("");
        kkeluar_tgl.setText("");
        kmasuk_jam.setText("");
        kmasuk_tgl.setText("");
        biaya.setText("");
        durasi.setText("");
        
    }
    public Utama() {
        initComponents();
        tengah tengah = new tengah(this);
        buka_database();
        tampil_parkir();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nopol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox();
        Simpan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cari = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kjenis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kmasuk_tgl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kmasuk_jam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kkeluar_jam = new javax.swing.JTextField();
        kkeluar_tgl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kbj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        durasi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        biaya = new javax.swing.JTextField();
        keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_parkir = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("No Plat");

        jLabel3.setText("Jenis");

        jenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Motor", "Mobil" }));

        Simpan.setText("SAVE");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nopol, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nopol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Masuk", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });

        jLabel4.setText("No Plat");

        kjenis.setEditable(false);
        kjenis.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                kjenisInputMethodTextChanged(evt);
            }
        });
        kjenis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kjenisKeyReleased(evt);
            }
        });

        jLabel5.setText("Jenis");

        kmasuk_tgl.setEditable(false);
        kmasuk_tgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kmasuk_tglKeyReleased(evt);
            }
        });

        jLabel6.setText("Tgl Masuk :");

        kmasuk_jam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kmasuk_jamKeyReleased(evt);
            }
        });

        jLabel7.setText("Jam :");

        kkeluar_jam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kkeluar_jamKeyReleased(evt);
            }
        });

        kkeluar_tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kkeluar_tglActionPerformed(evt);
            }
        });
        kkeluar_tgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kkeluar_tglKeyReleased(evt);
            }
        });

        jLabel8.setText("Tgl Keluar :");

        jLabel9.setText("Jam :");

        kbj.setEditable(false);
        kbj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbjActionPerformed(evt);
            }
        });
        kbj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kbjKeyReleased(evt);
            }
        });

        jLabel10.setText("B/J  :");

        jLabel11.setText("Durasi : ");

        durasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                durasiKeyReleased(evt);
            }
        });

        jLabel12.setText("Biaya:");

        biaya.setBackground(new java.awt.Color(255, 255, 153));
        biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaActionPerformed(evt);
            }
        });
        biaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                biayaKeyReleased(evt);
            }
        });

        keluar.setText("UPDATE");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kjenis)
                                    .addComponent(kmasuk_tgl, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kbj)
                                    .addComponent(kmasuk_jam)))
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kkeluar_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(biaya)
                            .addComponent(kkeluar_jam))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1358, 1358, 1358))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(keluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(kjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kbj, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(kmasuk_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kmasuk_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kkeluar_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kkeluar_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Keluar", jPanel2);

        tabel_parkir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_parkir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_parkirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_parkir);

        jLabel13.setText("   Felicia Gondawijaya(535140005)   -   Serliana(535140018)   -   Livia Margarita (535140031)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
    if( !"".equals(nopol.getText())){
    try{
        stat = conn.createStatement();
        String perintah="INSERT INTO parkir(nopol,jenis,tgl_masuk,jam_masuk) VALUES (upper('"+nopol.getText()+"'),'"+jenis.getSelectedItem()+"',CURDATE(),CURTIME());";
        stat.executeUpdate(perintah);
        JOptionPane.showMessageDialog(null,"Data save");
        nopol.getText();
        MasukKeServer();
        nopol.setText("");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Data failed to save");
        System.out.println("erornya : "+e);
    }
    tampil_parkir();
    }else{
        JOptionPane.showMessageDialog(null, "No Plat empty");
    }
}//GEN-LAST:event_SimpanActionPerformed

public void MasukKeServer() throws Exception
{
    try (Socket s = new Socket("192.168.43.141",9090))
        {
          
            BufferedReader in = new BufferedReader(new InputStreamReader(s.getInputStream()));
            PrintWriter out = new PrintWriter(s.getOutputStream(),true);
            String response = "",request = "";
            request = nopol.getText();
            //System.out.println(request);
            if(request!=null||request!="")
            {
             //System.out.println(request);   
             out.println(request + " Masuk");
            }
                
                
            
            
            
        }
    catch(Exception qw)
    {
               qw.printStackTrace();    
    }
    System.out.println("Connection Closed.");
}

private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
    cari_data();
}//GEN-LAST:event_cariKeyReleased

private void kjenisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kjenisKeyReleased
    
}//GEN-LAST:event_kjenisKeyReleased

private void kmasuk_tglKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kmasuk_tglKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_kmasuk_tglKeyReleased

private void kmasuk_jamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kmasuk_jamKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_kmasuk_jamKeyReleased

private void kkeluar_jamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kkeluar_jamKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_kkeluar_jamKeyReleased

private void kkeluar_tglKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kkeluar_tglKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_kkeluar_tglKeyReleased

private void kbjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kbjKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_kbjKeyReleased

private void durasiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durasiKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_durasiKeyReleased

private void biayaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_biayaKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_biayaKeyReleased

private void tabel_parkirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_parkirMouseClicked
    bersih();
    cari.setText(tabel_parkir.getValueAt(tabel_parkir.getSelectedRow(),1).toString());
    kjenis.setText(tabel_parkir.getValueAt(tabel_parkir.getSelectedRow(),2).toString());
    kmasuk_tgl.setText(tabel_parkir.getValueAt(tabel_parkir.getSelectedRow(),3).toString());
    kmasuk_jam.setText(tabel_parkir.getValueAt(tabel_parkir.getSelectedRow(),4).toString());
    
    try{
        stat = conn.createStatement();
        String perintah="SELECT tarif from kendaraan where jenis='"+kjenis.getText()+"'";
        set = stat.executeQuery(perintah);
        while(set.next()){
           kbj.setText(set.getString("tarif"));
        }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null ,"Gagal  ");
            System.out.println("Error :  "+e);
            System.exit(0);
        }
}//GEN-LAST:event_tabel_parkirMouseClicked

private void kjenisInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kjenisInputMethodTextChanged
    
}//GEN-LAST:event_kjenisInputMethodTextChanged

private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
    if( !"".equals(cari.getText())){
    try{
        stat = conn.createStatement();
        String perintah="update parkir set tgl_keluar=curdate(), jam_keluar=curtime() where nopol='"+cari.getText()+"'";
        stat.executeUpdate(perintah);
        JOptionPane.showMessageDialog(null,"Update succeed");
        KeluarKeServer();
        nopol.setText("");
        nopol.getText();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Failed to update");
        System.out.println("Error: "+e);
    }
    dapatkan_data();
    akumulasi_biaya();
    tampil_parkir();
    }else{
        JOptionPane.showMessageDialog(null, "No Plat empty");
    }
}//GEN-LAST:event_keluarActionPerformed

public void KeluarKeServer() throws Exception
{
    try (Socket s = new Socket("192.168.43.141",9090))
        {
          
            BufferedReader in = new BufferedReader(new InputStreamReader(s.getInputStream()));
            PrintWriter out = new PrintWriter(s.getOutputStream(),true);
            String response = "",request = "";
            request = cari.getText();
            //System.out.println(request);
            if(request!=null||request!="")
            {
             //System.out.println(request);   
             out.println(request + " Keluar");
            }
            
        }
    catch(Exception qw)
    {
               qw.printStackTrace();    
    }
    System.out.println("Connection Closed.");
}

    private void kbjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kbjActionPerformed

    private void kkeluar_tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kkeluar_tglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kkeluar_tglActionPerformed

    private void biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaActionPerformed
        // TODO add your handling code here:
        akumulasi_biaya();
    }//GEN-LAST:event_biayaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Utama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Simpan;
    private javax.swing.JTextField biaya;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField durasi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox jenis;
    private javax.swing.JTextField kbj;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kjenis;
    private javax.swing.JTextField kkeluar_jam;
    private javax.swing.JTextField kkeluar_tgl;
    private javax.swing.JTextField kmasuk_jam;
    private javax.swing.JTextField kmasuk_tgl;
    private javax.swing.JTextField nopol;
    private javax.swing.JTable tabel_parkir;
    // End of variables declaration//GEN-END:variables
}
